DogGo/Models/Owner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace DogGo.Models
{
    public class Owner
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        [DisplayName("Phone Number")]
        public string Phone { get; set; }
        public string Email { get; set; }
        [DisplayName("Neighborhood")]
        public int NeighborhoodId { get; set; }
        public Neighborhood Neighborhood { get; set; }
    }
}

DogGo/Controllers/DogController.cs
using DogGo.Models;
using DogGo.Models.ViewModels;
using DogGo.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Linq;

namespace DogGo.Controllers
{
    [Authorize]
    public class DogController : Controller
    {
        private readonly IDogRepository _dogRepository;
        private readonly IOwnerRepository _ownerRepository;

        public DogController(IDogRepository dogRepository, IOwnerRepository ownerRepository)
        {
            _dogRepository = dogRepository;
            _ownerRepository = ownerRepository;
        }

        // GET: DogController
        public ActionResult Index()
        {
            int ownerId = GetCurrentUserId();
            List<Dog> dogs = _dogRepository.GetDogByOwnerId(ownerId);
            return View(dogs);
        }

        // GET: DogController/Details/5
        public ActionResult Details(int id)
        {
            Dog dog = _dogRepository.GetDogById(id);

            if(dog.OwnerId != GetCurrentUserId())
            {
                return NotFound();
            }

            if (dog == null)
            {
                return NotFound();
            }
            return View(dog);
        }
        // GET: DogController/Create
        public ActionResult Create()
        {
            Dog dog = new Dog();
            return View(dog);
        }

        // POST: DogController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Dog dog)
        {
            try
            {
                // update the dogs OwnerId to the current user's Id 
                dog.OwnerId = GetCurrentUserId();

                _dogRepository.AddDog(dog);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(dog);
            }
        }

        // GET: DogController/Edit/5
        public ActionResult Edit(int id)
        {
            Dog dog = _dogRepository.GetDogById(id);
            int ownerId = GetCurrentUserId();
            List<Dog> userDogs = _dogRepository.GetDogByOwnerId(ownerId);

            if (dog == null || dog.OwnerId != ownerId)
            {
                return NotFound();
            }

            //check if dog in url is the user dog
           Dog foundDog = userDogs.Find(dog => dog.Id == id);

            if(foundDog == null)
            {
                return NotFound();
            }
            
            return View(dog);
        }

        // POST: DogController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Dog dog)
        {
            try
            {
                dog.OwnerId = GetCurrentUserId();
                _dogRepository.UpdateDog(dog);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(dog);
            }
        }

        // GET: DogController/Delete/5
        public ActionResult Delete(int id)
        {
            Dog dog = _dogRepository.GetDogById(id);

            if (dog.OwnerId != GetCurrentUserId())
            {
                return NotFound();
            }

            int ownerId = GetCurrentUserId();
            List<Dog> userDogs = _dogRepository.GetDogByOwnerId(ownerId);

            if (dog == null)
            {
                return NotFound();
            }

            //check if dog in url is the user dog
            Dog foundDog = userDogs.Find(dog => dog.Id == id);

            if (foundDog == null)
            {
                return NotFound();
            }

            return View(dog);
        }

        // POST: DogController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Dog dog)
        {
            try
            {
                _dogRepository.DeleteDog(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(dog);
            }
        }
        private int GetCurrentUserId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }
    }
}

DogGo/Controllers/OwnerController.cs
using DogGo.Models;
using DogGo.Models.ViewModels;
using DogGo.Repositories;
using DogGo.Repositories.Utils;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace DogGo.Controllers
{
    public class OwnerController : Controller
    {
        private readonly IOwnerRepository _ownerRepository;
        private readonly IDogRepository _dogRepository;
        private IWalkerRepository _walkerRepository;
        private INeighborhoodRepository _neighborhoodRepository;
        private IWalkRepository _walkRepository;

        // The constructor accepts an IConfiguration object as a parameter. This class comes from the ASP.NET framework and is useful for retrieving things out of the appsettings.json file like connection strings.
        public OwnerController(IConfiguration config)
        {
            _ownerRepository = new OwnerRepository(config);
            _dogRepository = new DogRepository(config);
            _walkerRepository = new WalkerRepository(config);
            _neighborhoodRepository = new NeighborhoodRepository(config);
            _walkRepository = new WalkRepository(config);

        }

        // GET: OwnerController
        public ActionResult Index()
        {
            int ownerId = GetCurrentUserId();

            return RedirectToAction(nameof(Details), new { id = ownerId });
        }

        // GET: OwnerController/Details/5
        public ActionResult Details(int id)
        {
            int currentUser = GetCurrentUserId();
            if (id != currentUser)
            {
                return NotFound();
            }

            Owner owner = _ownerRepository.GetOwnerById(id);
            List<Dog> dogs = _dogRepository.GetDogByOwnerId(owner.Id);
            List<Walker> walkers = _walkerRepository.GetWalkersInNeighborhood(owner.NeighborhoodId);
            List<Walk> walks = _walkRepository.GetWalksByOwnerId(currentUser);

            ProfileViewModel vm = new ProfileViewModel()
            {
                Owner = owner,
                Dogs = dogs,
                Walkers = walkers,
                Walks = walks
            };

            return View(vm);
        }

        // GET: OwnerController/Create
        public ActionResult Create()
        {
            List<Neighborhood> neighborhoods = _neighborhoodRepository.GetAll();

            OwnerFormViewModel vm = new OwnerFormViewModel()
            {
                Owner = new Owner(),
                Neighborhoods = neighborhoods
            };

            return View(vm);
        }

        // POST: OwnerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OwnerFormViewModel vm)
        {
            try
            {
                _ownerRepository.AddOwner(vm.Owner);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(vm);
            }

        }

        // GET: OwnerController/Edit/5
        public ActionResult Edit(int id)
        {
            int currentUser = GetCurrentUserId();
            if (id != currentUser)
            {
                return NotFound();
            }

            List<Neighborhood> neighborhoods = _neighborhoodRepository.GetAll();
            Owner owner = _ownerRepository.GetOwnerById(id);

            OwnerFormViewModel vm = new OwnerFormViewModel()
            {
                Neighborhoods = neighborhoods,
                Owner = owner
            };

            if (owner == null)
            {
                return NotFound();
            }
            return View(vm);
        }

        // POST: OwnerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, OwnerFormViewModel vm)
        {
            try
            {
                _ownerRepository.UpdateOwner(vm.Owner);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(vm);
            }
        }

        // GET: OwnerController/Delete/5
        public ActionResult Delete(int id)
        {
            int currentUser = GetCurrentUserId();
            if (id != currentUser)
            {
                return NotFound();
            }

            Owner owner = _ownerRepository.GetOwnerById(id);

            if (owner == null)
            {
                return NotFound();
            }

            return View(owner);
        }

        // POST: OwnerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Owner owner)
        {
            try
            {
                _ownerRepository.DeleteOwner(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(owner);
            }
        }
        private int GetCurrentUserId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }
    }
}

DogGo/Controllers/WalksController.cs
using DogGo.Models;
using DogGo.Models.ViewModels;
using DogGo.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;

namespace DogGo.Controllers
{
    public class WalksController : Controller
    {
        private readonly IWalkRepository _walkRepo;
        private readonly IWalkerRepository _walkerRepo;
        private readonly IDogRepository _dogRepo;

        public WalksController(IWalkRepository walksRepo, IWalkerRepository walkerRepo, IDogRepository dogRepo)
        {
            _walkRepo = walksRepo;
            _walkerRepo = walkerRepo;
            _dogRepo = dogRepo;
        }

        // GET: WalksController
        public ActionResult Index()
        {
            return View();
        }

        // GET: WalksController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: WalksController/Create
        public ActionResult Create(int walkerId)
        {
            int ownerId = GetCurrentUserId();
            List<Dog> dogs = _dogRepo.GetDogByOwnerId(ownerId);
            Walk walk = new Walk()
            {
                //add walker from anynomous object passed in Owner/Detail
                WalkerId = walkerId,
                Date = DateTime.Today
            };

            Walker walker = _walkerRepo.GetWalkerById(walkerId);
            WalksFormViewModel vm = new WalksFormViewModel()
            {
                Walker = walker,
                Walk = walk,
                Dogs = dogs
            };
            return View(vm);
        }

        // POST: WalksController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(WalksFormViewModel vm)
        {
            try
            {
                Walker walker = _walkerRepo.GetWalkerById(vm.Walk.WalkerId);
                vm.Walk.Walker = walker;
                vm.Walk.Duration = vm.Walk.Duration * 60;
                _walkRepo.AddWalk(vm.Walk);
                return RedirectToAction("Index", "Owner");

            }
            catch
            {
                return View(vm);
            }
        }

        // GET: WalksController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: WalksController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: WalksController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: WalksController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        private int GetCurrentUserId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }
    }
}

DogGo/Views/Owner/Create.cshtml
@model DogGo.Models.ViewModels.OwnerFormViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Owner</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Owner.Email" class="control-label"></label>
                <input asp-for="Owner.Email" class="form-control" />
                <span asp-validation-for="Owner.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Owner.Name" class="control-label"></label>
                <input asp-for="Owner.Name" class="form-control" />
                <span asp-validation-for="Owner.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Owner.Phone" class="control-label"></label>
                <input asp-for="Owner.Phone" class="form-control" />
                <span asp-validation-for="Owner.Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Owner.Address" class="control-label"></label>
                <input asp-for="Owner.Address" class="form-control" />
                <span asp-validation-for="Owner.Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Owner.NeighborhoodId" class="control-label"></label>
                <select asp-for="Owner.NeighborhoodId" class="form-control">
                    <option value="">Select Neighborhood</option>
                    @foreach (Neighborhood neighborhood in Model.Neighborhoods)
                    {
                        <option value="@neighborhood.Id">@neighborhood.Name</option>
                    }
                </select>
                <span asp-validation-for="Owner.NeighborhoodId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DogGo/Views/Owner/Delete.cshtml
@model DogGo.Models.Owner

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete @Model.Name?</h3>
<div>
    <h4>Owner</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NeighborhoodId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NeighborhoodId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DogGo/Views/Owner/Details.cshtml
@model DogGo.Models.ViewModels.ProfileViewModel

@{ ViewData["Title"] = "Profile"; }
<div>
    <h1 class="mb-4">@Model.Owner.Name</h1>

    <section class="container">
        <img style="width:100px;float:left;margin-right:20px"
             src="https://upload.wikimedia.org/wikipedia/commons/a/a0/Font_Awesome_5_regular_user-circle.svg" />
        <div>
            <label class="font-weight-bold">Address:</label>
            <span>@Model.Owner.Address</span>
        </div>
        <div>
            <label class="font-weight-bold">Phone:</label>
            <span>@Model.Owner.Phone</span>
        </div>
        <div>
            <label class="font-weight-bold">Email:</label>
            <span>@Model.Owner.Email</span>
        </div>
    </section>

    <hr class="mt-5" />
    <div class="clearfix"></div>

    <div class="row">
        <section class="col-7">
            <h2 class="text-left">Dogs</h2>
            <input type="button" class=" btn btn-success" value="Add Dog" onclick="location.href='@Url.Action("Create", "Dog")'" />

            <div class="row">
                @foreach (Dog dog in Model.Dogs)
                {
                    <div class="card m-1" style="width: 18rem;">
                        @if (String.IsNullOrEmpty(dog.ImageUrl))
                        {
                            <img src="https://cdn.pixabay.com/photo/2018/08/15/13/12/dog-3608037_960_720.jpg"
                                 class="card-img-top"
                                 alt="Doggo" />
                        }
                        else
                        {
                            <img src="@dog.ImageUrl" class="card-img-top" alt="Doggo" />
                        }
                        <div class="card-body">
                            <div>
                                <label class="font-weight-bold">Name:</label>
                                <span>@dog.Name</span>
                            </div>
                            <div>
                                <label class="font-weight-bold">Breed:</label>
                                <span>@dog.Breed</span>
                            </div>
                            <div>
                                <label class="font-weight-bold">Notes:</label>
                                <p>@dog.Notes</p>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <input type="button" class=" btn btn-secondary" value="Edit Dog" onclick="location.href='@Url.Action("Edit", "Dog")' + '/@dog.Id'" />
                                </div>
                                <div class="col">
                                    <input type="button" class=" btn btn-danger" value="Delete Dog" onclick="location.href='@Url.Action("Delete", "Dog")' +  '/@dog.Id'" />
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </section>

        <section class="col-5">
            <h4>Walkers Near Me</h4>

            <ul class="list-group mt-4">
                @foreach (Walker walker in Model.Walkers)
                {
                    <li class="list-group-item">
                        <img src="@walker.ImageUrl" style="width:50px" />
                        <span class="font-weight-bold ml-4">@walker.Name</span>
                        <input type="button" class="btn btn-secondary float-right" value="Schdule Walk" onclick="location.href='@Url.Action("Create", "Walks", new { walkerId = @walker.Id})'" />
                    </li>
                }
            </ul>

            <h4 class="mt-5">Upcoming Walks</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Walker</th>
                        <th scope="col">Dog</th>
                        <th scope="col">Time & Date</th>
                        <th scope="col">Confirmed</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Walk walk in Model.Walks)
                    {
                        <tr>
                            <th>@walk.Walker.Name</th>
                            <td>@walk.Dog.Name</td>
                            <td>@walk.Date</td>
                            <td>Pending</td>
                        </tr>
                    }
                </tbody>
            </table>
        </section>
    </div>
</div>

DogGo/Views/Owner/Edit.cshtml
@model DogGo.Models.ViewModels.OwnerFormViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Owner</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Owner.Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Owner.Name" class="control-label"></label>
                <input asp-for="Owner.Name" class="form-control" />
                <span asp-validation-for="Owner.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Owner.Address" class="control-label"></label>
                <input asp-for="Owner.Address" class="form-control" />
                <span asp-validation-for="Owner.Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Owner.Phone" class="control-label"></label>
                <input asp-for="Owner.Phone" class="form-control" />
                <span asp-validation-for="Owner.Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Owner.Email" class="control-label"></label>
                <input asp-for="Owner.Email" class="form-control" />
                <span asp-validation-for="Owner.Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Owner.NeighborhoodId" class="control-label"></label>
                <select asp-for="Owner.NeighborhoodId" class="form-control">
                    <option value="">Select Neighborhood</option>
                    @foreach (Neighborhood neighborhood in Model.Neighborhoods)
                    {
                        <option value="@neighborhood.Id">@neighborhood.Name</option>
                    }
                </select>
                <span asp-validation-for="Owner.NeighborhoodId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DogGo/Views/Owner/Index.cshtml
@model IEnumerable<DogGo.Models.Owner>

@{
    ViewData["Title"] = "Index";
}

<h1>Dog Owners</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm mb-4">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.Name)</h5>
                    <p class="card-text">Email: @Html.DisplayFor(modelItem => item.Email)</p>
                    <p class="card-text">Address: @Html.DisplayFor(modelItem => item.Address)</p>
                    <p class="card-text">Phone: @Html.DisplayFor(modelItem => item.Phone)</p>
                    <p class="card-text">Neighborhood: @Html.DisplayFor(modelItem => item.Neighborhood.Name)</p>

                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </div>
            </div>
        </div>
    }
</div>